language: android
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
  - "$HOME/.m2"
before_install:
- openssl aes-256-cbc -K $encrypted_7f6a0d70974a_key -iv $encrypted_7f6a0d70974a_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.1
  - android-26
  - extra-android-m2repository
  licenses:
  - android-sdk-license-.+
  - ".+"
jdk:
- oraclejdk8
branches:
  except:
  - gh-pages
notifications:
  email: false
env:
- PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1
- if [ ! -d ${HOME}/google-cloud-sdk ]; then curl https://sdk.cloud.google.com | bash;
  fi
install:
- gcloud config set project lottie-snapshots
script:
- "./gradlew check"
- "./gradlew connectedCheck"
sudo: false
